### ISSUE TITLE
Quotes are not handled

### ISSUE THREAD

**Issue by arwn** [geostran/risp#6]
# example 1
`# (let f (quote "hello")) -> "hello"`
`# (eval f) -> "hello"`
`# (eval "f") -> "hello"`
broken -> `# (eval "f\"") ->"hello"`
broken -> `# (eval "\"") -> (Err: expected '"', received EOF)`
# example 2
`# (let a (quote "hi")) -> "hi"`
`# a -> "hi"`
broken ->`# a"bigboy" -> "hi"`

**Comment by geostran** [comment]
For example 1:
`# (eval "f\"") ->"hello"`
is not broken because eval also takes a string of valid source code, parses it and then executes it.
`# (eval "\"") -> (Err: expected '"', received EOF)`
is not exactly broken, but the error message is wrong. After eval has parsed the string, it would try to   run an empty string, so it should return that it received EOF, but expected nothing. I need to fix that.

For example 2:
Not a bug either.
If you pass many elements to the repl, but they are not enclosed in a list, only the first element is evaluated. Also, strings are not space sensitive, so `a"bigboy"` is equal to `a "bigboy"` and since only the first element is evaluated, then a will be evaluated and the repl would return `"hi"`
